# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e4d6bb0cc45d5a36a2d504b9019da345a6a99b3598250dcff0acaf5bf219e312e8f6349c8426a8a1cd020db3372309cf24f56e53bf2227dbca17519602cf874

test:
  secret_key_base: b9b58d68df32dd2d45ab833b842ce08571bfaa540c666745867d754c0567325bf247fa798e3c0f7c2feb6d90c6e99f5e7505bbc10e78491edf5fde4825635fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
